### ISSUE TITLE
Update gatsby to new version

### ISSUE THREAD

**Issue by kiliw** [hardforkio/homepage-new#62]
Update gatsby to new version

**Comment by Levino** [comment]
Related to https://github.com/hardforkio/homepage-new/issues/42

Please carefully [read this](https://github.com/hardforkio/homepage-new/issues/42#issuecomment-417621867).

**Comment by EmCeeEs** [comment]
Official instructions: https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/

**Comment by kiliw** [comment]
Done in ##82.
